version: '3.1'
services:
  digital-db:
    image: postgres:14-alpine
    container_name: digital_db_container
    ports:
      - "6545:5432"
    environment:
      - POSTGRES_DB=digital-student
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql