CREATE TABLE grade
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    score      INTEGER,
    student_id BIGINT,
    date       date,
    subject    VARCHAR(255),
    CONSTRAINT pk_grade PRIMARY KEY (id),
    UNIQUE (student_id, subject)
);

CREATE TABLE student
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name  VARCHAR(255),
    second_name VARCHAR(255),
    age         INTEGER,
    email       VARCHAR(255),
    CONSTRAINT pk_student PRIMARY KEY (id)
);

ALTER TABLE grade
    ADD CONSTRAINT FK_GRADE_ON_STUDENT FOREIGN KEY (student_id) REFERENCES student (id);